import React, {useState} from 'react';
import {BookOpen, Clock3, Trophy, CalendarDays, Users, PlayCircle, Plus, Upload, Search, MoreHorizontal, CheckCircle2, AlertCircle, Sparkles, FileSpreadsheet, Download, Filter, Eye, Lock, Server, Database, HardDrive, ShieldCheck, Mail, Save, UserPlus, SlidersHorizontal} from 'lucide-react';
import {PortalHeader,Button,StatCard,Progress,Card,SectionTitle,Table,Badge,Field} from '../../components/portal/PortalUI';

export default function StudentDashboardPage(){return <><PortalHeader eyebrow="STUDENT PORTAL" title="Chào mừng trở lại, Ngọc Sơn 👋" desc="Tiếp tục lộ trình học tập và theo dõi tiến độ của bạn." actions={<Button><PlayCircle size={17}/> Tiếp tục học</Button>}/><div className="stats-grid">
<StatCard icon={BookOpen} label="Khóa học đang học" value="6" trend="+2 tháng này"/><StatCard icon={Clock3} label="Giờ học tuần này" value="12.5h" trend="+18%"/><StatCard icon={Trophy} label="Điểm trung bình" value="8.6" trend="+0.4"/><StatCard icon={CalendarDays} label="Bài sắp đến hạn" value="4" sub="Trong 7 ngày"/></div>
<div className="dashboard-grid"><Card><SectionTitle title="Tiến độ học tập" action={<Button variant="ghost">Xem chi tiết</Button>}/>{[['IELTS Intensive Reading',78],['Lập trình Web',62],['Cơ sở dữ liệu',45]].map(x=><div className="progress-row" key={x[0]}><div><b>{x[0]}</b><span>{x[1]}%</span></div><Progress value={x[1]}/></div>)}</Card>
<Card><SectionTitle title="Việc cần làm"/><div className="task-list">{['Quiz Chương 4 — Cơ sở dữ liệu','Assignment React UI','IELTS Reading Test 04','Bài thảo luận tuần 6'].map((x,i)=><div className="task" key={x}><div className="task-dot"/><div><b>{x}</b><small>{i+1} ngày nữa · {i%2?'Bài tập':'Quiz'}</small></div><span>›</span></div>)}</div></Card></div>
<Card><SectionTitle title="Khóa học gần đây" action={<Button variant="ghost">Tất cả khóa học</Button>}/><div className="course-grid">{['Lập trình React thực chiến','IELTS Intensive Reading','Kiến trúc máy tính'].map((x,i)=><div className="course-mini" key={x}><div className={`course-cover c${i}`}>{i===0?'REACT':i===1?'IELTS':'IT'}</div><div><Badge tone="green">Đang học</Badge><h3>{x}</h3><Progress value={[62,78,45][i]}/><small>{[18,32,12][i]}/{[28,40,26][i]} bài học</small></div></div>)}</div></Card></>}
