import React, {useState} from 'react';
import {BookOpen, Clock3, Trophy, CalendarDays, Users, PlayCircle, Plus, Upload, Search, MoreHorizontal, CheckCircle2, AlertCircle, Sparkles, FileSpreadsheet, Download, Filter, Eye, Lock, Server, Database, HardDrive, ShieldCheck, Mail, Save, UserPlus, SlidersHorizontal} from 'lucide-react';
import {PortalHeader,Button,StatCard,Progress,Card,SectionTitle,Table,Badge,Field} from '../../components/portal/PortalUI';

export default function UserManagementPage(){const [show,setShow]=useState(false);return <><PortalHeader eyebrow="RBAC" title="Quản lý người dùng" desc="Quản lý tài khoản, vai trò và trạng thái truy cập." actions={<Button onClick={()=>setShow(true)}><UserPlus size={17}/> Tạo tài khoản</Button>}/><div className="filter-bar"><div className="tabs"><button className="tab active">Tất cả 4,386</button><button className="tab">Student 3,842</button><button className="tab">Teacher 326</button><button className="tab">Manager 42</button><button className="tab">Admin 16</button></div><div className="search-mini"><Search size={16}/><input placeholder="Tìm email/tên..."/></div></div><Card><Table headers={['Người dùng','Email','Vai trò','Đăng nhập gần nhất','Trạng thái','']} rows={[
['Nguyễn Hà Anh','haanh@eduverse.vn','Student','01/10/2026 22:14','active'],
['Nguyễn Minh Anh','minhanh@eduverse.vn','Teacher','01/10/2026 21:52','active'],
['Trần Thu Hà','thuha@eduverse.vn','Teacher','01/10/2026 20:12','active'],
['Lê Quốc Bảo','quocbao@eduverse.vn','Manager','01/10/2026 18:42','active'],
['Nguyễn Admin','admin@eduverse.vn','Admin','01/10/2026 23:48','active']
].map((r,i)=>[<div className="table-user"><div className="avatar sm">NS</div><b>{r[0]}</b></div>,r[1],<Badge tone={r[2]==='Admin'?'purple':r[2]==='Manager'?'orange':r[2]==='Teacher'?'blue':'green'}>{r[2]}</Badge>,r[3],<Badge tone="green">Hoạt động</Badge>,<MoreHorizontal/>])}/></Card>{show&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>Tạo tài khoản đặc quyền</h2><button onClick={()=>setShow(false)}>×</button></div><Field label="Họ tên" placeholder="Nguyễn Văn A"/><Field label="Email" placeholder="user@eduverse.vn"/><Field label="Vai trò" value="Teacher"/><Field label="Mật khẩu tạm thời" placeholder="••••••••"/><div className="modal-actions"><Button variant="secondary" onClick={()=>setShow(false)}>Hủy</Button><Button onClick={()=>setShow(false)}>Tạo tài khoản</Button></div></div></div>}</>}
